# Generated by Django 2.1.5 on 2019-01-21 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 33, 52, 927783, tzinfo=utc), verbose_name='Publicado'),
        ),
    ]
